server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  
  static_configs:
  - targets:
      - localhost  
    labels:
      job: logs
      __path__: "/EventsServer/*.log"
  
  pipeline_stages:
  - json:
      expressions:
        timestamp: time
        instance: id
  - labels:
      instance:
  - timestamp:
      source: timestamp
      format: RFC3339Nano
  
